api:
    resource: "@IdeasApiBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

overview:
  path: /ideas/overview
  defaults: { _controller: IdeasBundle:Ideas:overview}

ideas_list:
  path: /ideas
  defaults: { _controller: IdeasBundle:Ideas:list}

ideas_add:
  path: /ideas/add
  defaults: { _controller: IdeasBundle:Ideas:add, _format: html }

ideas_show:
  path: /ideas/{idea}.{_format}
  defaults: { _controller: IdeasBundle:Ideas:show, _format: html}

ideas_update:
  path: /ideas/update/{idea_id}
  defaults: { _controller: IdeasBundle:Ideas:update }

ideas_remove:
  path: /ideas/remove/{idea_id}
  defaults: { _controller: IdeasBundle:Ideas:remove }

admin:
  path: /admin
  defaults: { _controller: IdeasBundle:Default:admin }

logout:
  path: /logout

about:
  path: /about
  defaults: { _controller: IdeasBundle:Ideas:about}

users:
  path: /users/list
  defaults: { _controller: IdeasBundle:User:list}