# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
#    role_hierarchy:
#      ROLE_ADMIN: ROLE_USER
#      ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
              users:
                oleg:
                  password: $2y$12$NXnISGwmt7JVhmoUwRCJgeXi3bW/FvTfBcVd4TCXd5mHVeEUT0xju
                  roles: 'ROLE_ADMIN'
                mariana:
                  password: $2y$12$owKAvsGnqG72phvkzE42JurRBQH.1oemQMSvP./PzvwSWz9INtPfu
                  roles: 'ROLE_USER'

    encoders:
      Symfony\Component\Security\Core\User\User:
        #plaintext
        algorithm: bcrypt
        cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        secured_area:
#            # ...
#            logout:
#                path:   /logout
#                target: /

#        main:
#            anonymous: ~

        default:
            anonymous: ~
            http_basic: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
    access_control:
      # - { path: ^/ideas/update, roles: ROLE_ADMIN }
      # - { path: ^/ideas/delete, roles: ROLE_ADMIN }
      # - { path: ^/ideas/add, roles: ROLE_ADMIN }
      # - { path: ^/ideas/, roles: [ROLE_ADMIN,ROLE_USER] }
      # - { path: ^/admin, roles: ROLE_ADMIN }
      # - { path: ^/home, roles: [ROLE_ADMIN,ROLE_USER] }
