# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
  app.mailer.transport: sendmail
  app.newsletter_manager.logger: loggasdfer

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  IdeasBundle\Controller\:
    resource: '../../src/IdeasBundle/Controller'
    public: true
    tags: ['controller.service_arguments']

  #AppBundle\Service\FileUploader:
  app.file_uploader:
    class: AppBundle\Service\FileUploader
    arguments:
      $targetDir: '%ideas_images%'

  AppBundle\Service\:
    resource: '../../src/AppBundle/Service'
    public: true
    tags: ['controller.service_arguments']

  AppBundle\Service\Mailer:
    arguments:
      $type: 'type'

  AppBundle\Service\FileUploader: '@app.file_uploader'

#    service_name:
#        class: IdeasBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  #app.file_uploader:
    #arguments:
      #$targetDir: '%ideas_images%'

  app.mailer:
    class: AppBundle\Service\Mailer
    arguments: ['%app.mailer.transport%']

  app.newsletter_manager:
    class: AppBundle\Service\NewsLetterManager
#    arguments: ['@app.mailer']
    calls:
     - [setMailer, ['@app.mailer']]
     - [setLogger, ['%app.newsletter_manager.logger%']]

