# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
  app.mailer.transport: sendmail
  app.newsletter_manager.logger: loggasdfer
services:
#    service_name:
#        class: IdeasBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

  app.mailer:
    class: IdeasBundle\Service\Mailer
    arguments: ['%app.mailer.transport%']

  app.newsletter_manager:
    class: IdeasBundle\Service\NewsLetterManager
#    arguments: ['@app.mailer']
    calls:
     - [setMailer, ['@app.mailer']]
     - [setLogger, ['%app.newsletter_manager.logger%']]

  IdeasBundle\Service\FileUploader:
    arguments:
      $targetDir: '%ideas_images%'