IdeasBundle\Entity\Idea:
    type: entity
    table: ideas
    repositoryClass: IdeasBundle\Repository\IdeaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: string
            length: 255
        attractiveness:
            type: integer
            length: 2
            nullable: true
        created_at:
            type: datetime
        image:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks: {  }
