AppBundle\Entity\Idea:
    type: entity
    table: ideas
    repositoryClass: AppBundle\Repository\IdeaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        keywords:
          targetEntity: Keyword
          cascade: [persist, remove]
          mappedBy: idea
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        attractiveness:
            type: integer
            length: 2
            nullable: true
        created_at:
            type: datetime
        image:
            type: string
            length: 255
            nullable: true
    lifecycleCallbacks:
      prePersist: [setCreatedAt]
